### ISSUE TITLE
[GraphQL Plugin] Add support for GraphQL Cursor Connections Specification

### ISSUE THREAD

**Issue by taras** [thefrontside/playhouse#68]
# Motivation

As a developer using the GraphQL API provided by the GraphQL plugin, I need to be able to query many entities with filtering. The standard for querying many entities via a GraphQL API is described in [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm). We need to allow querying records using Schema and resolvers that conform to GraphQL Cursor Connections Specification.

# Approach

There is nothing stopping someone from implementing the connection specification manually. For example, if there is type called Repositories that has the following schema,

```graphql
type Repository @extend(type: "Entity") {
  owner: User
  url: String
}
```

Someone familiar with GraphQL Cursor Connections Specification could write the following types to make it possible to query repositories that are owned by a specific user.

```graphql
type PageInfo {
  startCursor: String!
  endCursor: String!
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

type RepositoryEdge {
  node: Repository!
  cursor: String!
}

type RepositoryConnection {
  edges: [RepositoryEdge]
  pageInfo: PageInfo!
}

extend User {
  repositories: RepositoryConnection
}
```

After they implement resolvers, they would be able to query records using the following query

```graphql
{
  owner {
    repositories(first: 100) {
       edges {
          node {
            ... on Repository {
              url
            }
          }
       }
    }
   }
}
```

This process requires
1. Writing the correct schema
2. Writing the resolvers

We can make this process simpler by allowing to define these connection using a directive. Instead of all these steps, we'd do the following,

```graphql
extend User {
  repositories: Repository @connection() @relation(type: "ownedBy")
}
```

This will automatically expand into the schema example schema and implement the necessary resolvers.

**Comment by wKich** [comment]
We implemented it in #112 

But final syntax was changed. Instead of
```graphql
extend User {
  repositories: Repository @connection() @relation(type: "ownedBy")
}
```

should be used
```graphql
extend User {
  repositories: Connection @relation(type: "ownedBy", interface: "Repository")
}
```
