### ISSUE TITLE
[Incremental Ingestion Backend] We shouldn't commit when there are no entities

### ISSUE THREAD

**Issue by taras** [thefrontside/playhouse#94]
Incremental Ingestion Backend should only attempt to insert marks when there are entities to mark. In our close source version, we added the following code

```ts
    if (entities.length > 0) {
      await tx('ingestion.ingestion_mark_entities').insert(
        entities.map(entity => ({
          id: v4(),
          ingestion_mark_id: markId,
          ref: stringifyEntityRef(entity.entity),
        })),
      );
    }
```

**Comment by cowboyd** [comment]
What effect does this `if` statement have? My surmise would be none, so I'm surprised by it. It wouldn't be the first time `knex` did something counter-intuitive though.

**Comment by taras** [comment]
It throws a query error when you try to insert no data.

**Comment by cowboyd** [comment]
I see. This should only happen on the very first page, and when the ingestion is `done`. If these two conditions are not met, then it is very likely a bug in the provider. Should be a warning at the very least.

**Comment by taras** [comment]
When we're paginating two cursors simultaneously, there can be many pages with no results. For example, we have these use cases today when ingesting all repositories from all organizations. We paginate through one organization at a time; for each organization, we paginate through its repositories. Some organizations don't have repositories, in this case, we would have no entities to commit for one of the pages.

**Comment by taras** [comment]
It's a bit of a mind fook.

**Comment by wKich** [comment]
Previously we had:
```js
for (const entity of entities) {
      await tx('ingestion.ingestion_mark_entities').insert({
        id: v4(),
        ingestion_mark_id: markId,
        ref: stringifyEntityRef(entity.entity),
      });
    }
```
It doesn't commit if entities is empty. So the only difference with closed source code it does insertion in one transaction

**Comment by cowboyd** [comment]
I see. Very interesting.
> It's a bit of a mind fook.

Hmmmm....This has me thinking. Essentially, it sounds like the situation is that our stream is an OUTER join between GitHub organizations and repositories, which means that it contains a lot of "null" values. However, what would make our implementation simpler, is if we could somehow process it as an INNER join, which would be being able to somehow compose incremental ingestion streams. Very hand-wavy, but an avenue of research to explore for ingestion / catalog 2.0

**Comment by taras** [comment]
> if we could somehow process it as an INNER join, which would be being able to somehow compose incremental ingestion streams

This would be wonderful and directly applicable to this use case because GitHub Enterprise has an `organizations` query that allows us to paginate both organizations and repositories simultaneously. 

GitHub.com doesn't have an 'organizations' query, so we have to use the `GET /organizations` REST endpoint with a different pagination logic. 

We must duplicate the repository fetching with the current setup because organization fetching is different. Ideally, we could inverse it so that repositories are the same but organizations fetching is different. It would also be great if we could emit organizations while fetching repositories so we don't have to duplicate it.
